name: E2E — Cross-browser + Parallel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      cibuuid: ${{ steps.id.outputs.cibuuid }}
    steps:
      - name: Generate ci-build-id
        id: id
        run: |
          echo "cibuuid=sha-${GITHUB_SHA}-time-$(date +%s)" >> $GITHUB_OUTPUT

  install:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci

  cypress-run:
    needs: install
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox, webkit]  # cross-browser
        worker: [1,2]                       # number of parallel workers per browser (adjust to 1-3)
    steps:
      - uses: actions/checkout@v4

      - name: Run Cypress (record + parallel)
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}
          record: true
          parallel: true
          ci-build-id: ${{ needs.prepare.outputs.cibuuid }}-${{ matrix.browser }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
